title = "Home"
baseURL = "https://seralouk.github.io/personal-website/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
publishDir = "docs"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/seralouk/"
  youtube = ""
  github = "https://github.com/seralouk"
  linkedin = "https://www.linkedin.com/in/serafeim-loukas-041553104/"
  

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
